alias gst="git status"
alias gsh="git stash"
alias gshp="git stash pop"
alias gshl="git stash list"
alias gbr="git branch"
alias glo="git log --oneline | head"
alias gpl="git pull"
alias gplo="git pull origin"
alias gcp="git cherry-pick"
alias grb="git rebase"
alias grbi="git rebase --interactive"
alias gdf="git diff"
alias gdfc="git diff --cached"
alias gps="git push"
alias gpsf="git push --force"
alias gpsod="git push origin develop"
alias gco="git checkout"
alias gad="git add"
alias gci="git commit"
alias gcia="git commit --amend"
alias grs="git reset"
alias grsh="git reset --hard"
alias grshod="git fetch && git checkout develop && git reset --hard origin/develop"
alias grshom="git fetch && git checkout master && git reset --hard origin/master"
alias grshodm="git fetch && git checkout develop && git reset --hard origin/develop && git checkout master && git reset --hard origin/master"
alias glop="git fetch && git log --pretty=format:'%C(yellow)%h | %Cred%ad | %C(cyan)%an | %Creset%s' --date=short ^origin/master origin/develop --no-merges"

alias gg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"

